import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Header from "../components/Header";
import useUser from "../utils/useUser";

const Admin: NextPage = () => {
  const { user } = useUser({
    redirectTo: "/login",
  });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main>
        <h1>
          Admin Console
        </h1>
      </main>
    </div>
  )
}

export default Admin
