import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Header from "../components/Header";
import useUser from "../utils/useUser";
import useSWR from "swr"
import axios from "axios"
import AdminTable from "../components/AdminTable";

const Admin: NextPage = () => {
  const { user } = useUser({
    redirectTo: "/login",
  });

  async function fetcher(url: string) {
    const res = await axios.get(url);
    console.log(res);
    return res.data.orders;
  }

  const {data, error} = useSWR("/api/getAll", fetcher, {refreshInterval : 5000});

  return (
    <div>
      <Head>
        <title>Samfah Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/samfah-logo.jpg" />
      </Head>
      <Header/>
      <main className="px-2 md:px-16 py-5">
        <AdminTable orders={data}/>
      </main>
    </div>
  )
}

export default Admin
