import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import ShopHeader from "../components/ShopHeader"
import {products} from "../lib/products"
import ProductCard from "../components/ProductCard";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/samfah-logo.jpg" />
      </Head>
      <ShopHeader/>
      <main >

        <div className="grid grid-cols-3 gap-4 p-4 mx-auto">
          {products.map((product, id) => (
            <ProductCard key={id} name={product.name} url={product.url} price={product.price}/>
          ))}
        </div>
      </main>
    </div>
  )
}

export default Home
